version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fernando.jaques@outlook.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - 8089:80
    depends_on:
      - postgres
    networks:
      - postgres-compose-network


networks:
  postgres-compose-network:
    driver: bridge

volumes:
  postgres_data:

